#ifndef MPFUN_TEST_REFERENCE_VALUES_HPP
#define MPFUN_TEST_REFERENCE_VALUES_HPP

/**
 * @file reference_values.hpp
 * @brief Reference values computed by Fortran MPFUN for validation.
 * 
 * These values are generated by tests/fortran_reference/generate_reference.f90
 * and should be regenerated if the reference Fortran implementation changes.
 * 
 * Format: Each value is stored as a string to preserve full precision.
 */

#include <string>
#include <vector>

namespace mpfun::test {

// ============================================================================
// Constants (100+ digit precision)
// ============================================================================

/// Pi to 100 digits
constexpr const char* PI_100 = 
    "3.1415926535897932384626433832795028841971693993751"
    "058209749445923078164062862089986280348253421170679";

/// e (Euler's number) to 100 digits
constexpr const char* E_100 = 
    "2.7182818284590452353602874713526624977572470936999"
    "595749669676277240766303535475945713821785251664274";

/// log(2) to 100 digits
constexpr const char* LN2_100 = 
    "0.6931471805599453094172321214581765680755001343602"
    "552541206800094933936219696947156058633269964186875";

/// Euler-Mascheroni constant to 100 digits
constexpr const char* EULER_GAMMA_100 = 
    "0.5772156649015328606065120900824024310421593359399"
    "235988057672348848677267776646709369470632917467495";

// ============================================================================
// Arithmetic Test Cases
// ============================================================================

struct ArithmeticTestCase {
    std::string a;
    std::string b;
    std::string sum;        // a + b
    std::string diff;       // a - b
    std::string product;    // a * b
    std::string quotient;   // a / b
};

// TODO: Fill these from Fortran reference output
inline std::vector<ArithmeticTestCase> get_arithmetic_test_cases() {
    return {
        // Case 1: Simple integers
        {
            "2.0",
            "3.0",
            "5.0",
            "-1.0",
            "6.0",
            "0.66666666666666666666666666666666666666666666666667"
        },
        // Case 2: Pi and e
        {
            PI_100,
            E_100,
            "", // TODO: Compute with Fortran
            "",
            "",
            ""
        },
        // More cases to be added by running generate_reference.f90
    };
}

// ============================================================================
// Transcendental Test Cases
// ============================================================================

struct TranscendentalTestCase {
    std::string x;
    std::string expected;
};

// TODO: Fill from Fortran reference
inline std::vector<TranscendentalTestCase> get_exp_test_cases() {
    return {
        {"0.0", "1.0"},
        {"1.0", E_100},
        // More cases
    };
}

inline std::vector<TranscendentalTestCase> get_log_test_cases() {
    return {
        {"1.0", "0.0"},
        {E_100, "1.0"},
        {"2.0", LN2_100},
        // More cases
    };
}

inline std::vector<TranscendentalTestCase> get_sin_test_cases() {
    return {
        {"0.0", "0.0"},
        // sin(pi/6) = 0.5
        {"0.5235987755982988730771072305465838140328615665625", "0.5"},
        // More cases
    };
}

inline std::vector<TranscendentalTestCase> get_cos_test_cases() {
    return {
        {"0.0", "1.0"},
        // cos(pi/3) = 0.5
        {"1.0471975511965977461542144610931676280657231331250", "0.5"},
        // More cases
    };
}

inline std::vector<TranscendentalTestCase> get_sqrt_test_cases() {
    return {
        {"0.0", "0.0"},
        {"1.0", "1.0"},
        {"4.0", "2.0"},
        {"2.0", "1.4142135623730950488016887242096980785696718753769"
                "480731766797379907324784621070388503875343276415727"},
        // More cases
    };
}

} // namespace mpfun::test

#endif // MPFUN_TEST_REFERENCE_VALUES_HPP
