/**
 * @file run_validation.cpp
 * @brief Validation runner for MPFloat operations against reference data
 * 
 * Reads test data generated by generate_test_data.py and validates
 * MPFloat operations against the high-precision reference values.
 * 
 * Usage:
 *   run_validation <test_data.bin> [--verbose] [--op <operation>] [--tolerance <words>]
 * 
 * Copyright (c) 2024 Argonne National Laboratory
 */

#include <iostream>
#include <iomanip>
#include <string>
#include <cstring>
#include <cstdlib>

#include "test_data_reader.hpp"

#include "mpfun/mpfun.hpp"

using namespace mpfun;
using namespace mpfun::validation;

// Configuration
struct Config {
    std::string input_file;
    bool verbose = false;
    int tolerance_words = 2;
    Operation filter_op = static_cast<Operation>(255);  // 255 = all
    bool filter_enabled = false;
};

void print_usage(const char* prog) {
    std::cerr << "Usage: " << prog << " <test_data.bin> [options]\n"
              << "\nOptions:\n"
              << "  --verbose, -v       Print detailed output for each test\n"
              << "  --op <name>         Filter by operation (add/sub/mul/div/sqrt/exp/log/sin/cos/tan/atan)\n"
              << "  --tolerance <n>     Allow n least-significant words to differ (default: 2)\n"
              << "  --help, -h          Show this help\n";
}

Operation parse_operation(const std::string& name) {
    if (name == "add") return Operation::Add;
    if (name == "sub") return Operation::Sub;
    if (name == "mul") return Operation::Mul;
    if (name == "div") return Operation::Div;
    if (name == "sqrt") return Operation::Sqrt;
    if (name == "exp") return Operation::Exp;
    if (name == "log") return Operation::Log;
    if (name == "sin") return Operation::Sin;
    if (name == "cos") return Operation::Cos;
    if (name == "tan") return Operation::Tan;
    if (name == "atan") return Operation::Atan;
    throw std::runtime_error("Unknown operation: " + name);
}

Config parse_args(int argc, char* argv[]) {
    Config cfg;
    
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        
        if (arg == "--help" || arg == "-h") {
            print_usage(argv[0]);
            std::exit(0);
        } else if (arg == "--verbose" || arg == "-v") {
            cfg.verbose = true;
        } else if (arg == "--op" && i + 1 < argc) {
            cfg.filter_op = parse_operation(argv[++i]);
            cfg.filter_enabled = true;
        } else if (arg == "--tolerance" && i + 1 < argc) {
            cfg.tolerance_words = std::atoi(argv[++i]);
        } else if (arg[0] != '-') {
            cfg.input_file = arg;
        } else {
            std::cerr << "Unknown option: " << arg << "\n";
            print_usage(argv[0]);
            std::exit(1);
        }
    }
    
    if (cfg.input_file.empty()) {
        std::cerr << "Error: No input file specified\n";
        print_usage(argv[0]);
        std::exit(1);
    }
    
    return cfg;
}

/**
 * @brief Convert MPFloatData to MPFloat<WORDS>
 */
template <int WORDS>
MPFloat<WORDS> to_mpfloat(const MPFloatData& data) {
    MPFloat<WORDS> result;
    int64_t* dest = result.data();
    
    // Set metadata
    dest[0] = WORDS;  // allocated
    dest[1] = WORDS;  // precision
    
    // Copy sign_length and exponent
    dest[2] = data.words.size() > 0 ? data.words[0] : 0;
    dest[3] = data.words.size() > 1 ? data.words[1] : 0;
    
    // Copy mantissa
    size_t mantissa_words = data.words.size() > 2 ? data.words.size() - 2 : 0;
    for (size_t i = 0; i < mantissa_words && static_cast<int>(i) < WORDS; ++i) {
        dest[4 + i] = data.words[2 + i];
    }
    
    // Zero remaining
    for (size_t i = mantissa_words; static_cast<int>(i) < WORDS; ++i) {
        dest[4 + i] = 0;
    }
    
    return result;
}

/**
 * @brief Convert MPFloat<WORDS> to MPFloatData
 */
template <int WORDS>
MPFloatData from_mpfloat(const MPFloat<WORDS>& mp) {
    MPFloatData data;
    const int64_t* src = mp.data();
    
    data.words.resize(WORDS + 2);
    data.words[0] = src[2];  // sign_length
    data.words[1] = src[3];  // exponent
    
    for (int i = 0; i < WORDS; ++i) {
        data.words[2 + i] = src[4 + i];
    }
    
    return data;
}

/**
 * @brief Run a single test case
 */
template <int WORDS>
bool run_test(const TestCase& tc, const Config& cfg, int case_num) {
    MPFloatData actual_data;
    
    try {
        switch (tc.operation) {
            case Operation::Add: {
                auto a = to_mpfloat<WORDS>(tc.inputs[0]);
                auto b = to_mpfloat<WORDS>(tc.inputs[1]);
                auto result = a + b;
                actual_data = from_mpfloat(result);
                break;
            }
            case Operation::Sub: {
                auto a = to_mpfloat<WORDS>(tc.inputs[0]);
                auto b = to_mpfloat<WORDS>(tc.inputs[1]);
                auto result = a - b;
                actual_data = from_mpfloat(result);
                break;
            }
            case Operation::Mul: {
                auto a = to_mpfloat<WORDS>(tc.inputs[0]);
                auto b = to_mpfloat<WORDS>(tc.inputs[1]);
                auto result = a * b;
                actual_data = from_mpfloat(result);
                break;
            }
            case Operation::Div: {
                auto a = to_mpfloat<WORDS>(tc.inputs[0]);
                auto b = to_mpfloat<WORDS>(tc.inputs[1]);
                auto result = a / b;
                actual_data = from_mpfloat(result);
                break;
            }
            case Operation::Sqrt: {
                auto a = to_mpfloat<WORDS>(tc.inputs[0]);
                auto result = sqrt(a);
                actual_data = from_mpfloat(result);
                break;
            }
            // Transcendental functions - check if available
            case Operation::Exp:
            case Operation::Log:
            case Operation::Sin:
            case Operation::Cos:
            case Operation::Tan:
            case Operation::Atan: {
                // These may not be implemented yet
                if (cfg.verbose) {
                    std::cout << "  [SKIP] " << operation_name(tc.operation) 
                              << " not implemented\n";
                }
                return true;  // Skip, don't count as failure
            }
            default:
                std::cerr << "Unknown operation: " << static_cast<int>(tc.operation) << "\n";
                return false;
        }
    } catch (const std::exception& e) {
        std::cerr << "Exception in test case " << case_num << ": " << e.what() << "\n";
        return false;
    }
    
    // Compare result
    bool pass = approximately_equal(actual_data, tc.expected, cfg.tolerance_words);
    int matched = matching_words(actual_data, tc.expected);
    
    if (cfg.verbose || !pass) {
        std::cout << "Case " << std::setw(4) << case_num << " [" 
                  << std::setw(5) << operation_name(tc.operation) << "]: ";
        
        if (pass) {
            std::cout << "PASS (matched " << matched << " words)\n";
        } else {
            std::cout << "FAIL (matched " << matched << " words)\n";
            
            // Print details
            std::cout << "  Expected: sign_len=" << tc.expected.sign_length()
                      << " exp=" << tc.expected.exponent() << " mantissa=[";
            for (int i = 0; i < std::min(4, tc.expected.length()); ++i) {
                if (i > 0) std::cout << ", ";
                std::cout << std::hex << tc.expected.words[2 + i] << std::dec;
            }
            std::cout << "...]\n";
            
            std::cout << "  Actual:   sign_len=" << actual_data.sign_length()
                      << " exp=" << actual_data.exponent() << " mantissa=[";
            for (int i = 0; i < std::min(4, actual_data.length()); ++i) {
                if (i > 0) std::cout << ", ";
                std::cout << std::hex << actual_data.words[2 + i] << std::dec;
            }
            std::cout << "...]\n";
        }
    }
    
    return pass;
}

// C++17-compatible helper: runs all test cases for a given MPFloat word size
template <int WORDS>
void run_all_cases(const std::vector<TestCase>& cases, const Config& cfg,
                   int& passed, int& failed) {
    for (size_t i = 0; i < cases.size(); ++i) {
        bool result = run_test<WORDS>(cases[i], cfg, static_cast<int>(i + 1));
        if (result) passed++;
        else failed++;
    }
}

int main(int argc, char* argv[]) {
    Config cfg = parse_args(argc, argv);
    
    std::cout << "MPFloat Validation Runner\n";
    std::cout << "========================\n\n";
    
    // Read test data
    TestDataReader reader;
    std::vector<TestCase> cases;
    
    try {
        cases = reader.read_file(cfg.input_file);
    } catch (const std::exception& e) {
        std::cerr << "Error reading test data: " << e.what() << "\n";
        return 1;
    }
    
    const auto& header = reader.header();
    std::cout << "Test file: " << cfg.input_file << "\n";
    std::cout << "Precision: ~" << header.approx_decimal_digits() << " decimal digits\n";
    std::cout << "Words per number: " << header.words_per_number << "\n";
    std::cout << "Total cases: " << cases.size() << "\n";
    std::cout << "Tolerance: " << cfg.tolerance_words << " words\n\n";
    
    // Filter if requested
    if (cfg.filter_enabled) {
        cases = TestDataReader::filter_by_op(cases, cfg.filter_op);
        std::cout << "Filtered to " << operation_name(cfg.filter_op) 
                  << ": " << cases.size() << " cases\n\n";
    }
    
    // Run tests based on precision
    // We need to select the right MPFloat instantiation based on words_per_number
    int mantissa_words = static_cast<int>(header.words_per_number) - 2;
    
    int passed = 0;
    int failed = 0;
    int skipped = 0;
    
    // Select MPFloat size based on file's words_per_number and run all cases
    if (mantissa_words <= 6) {
        std::cout << "Using MPFloat<6> (~100 digits)\n\n";
        run_all_cases<6>(cases, cfg, passed, failed);
    } else if (mantissa_words <= 12) {
        std::cout << "Using MPFloat<12> (~200 digits)\n\n";
        run_all_cases<12>(cases, cfg, passed, failed);
    } else if (mantissa_words <= 28) {
        std::cout << "Using MPFloat<28> (~500 digits)\n\n";
        run_all_cases<28>(cases, cfg, passed, failed);
    } else if (mantissa_words <= 56) {
        std::cout << "Using MPFloat<56> (~1000 digits)\n\n";
        run_all_cases<56>(cases, cfg, passed, failed);
    } else {
        std::cerr << "Error: Test data requires " << mantissa_words
                  << " words, but max supported is 56\n";
        return 1;
    }
    
    // Summary
    std::cout << "\n========================\n";
    std::cout << "Results: " << passed << " passed, " << failed << " failed";
    if (skipped > 0) std::cout << ", " << skipped << " skipped";
    std::cout << "\n";
    
    if (failed == 0) {
        std::cout << "✓ All tests passed!\n";
        return 0;
    } else {
        std::cout << "✗ Some tests failed.\n";
        return 1;
    }
}
