/**
 * @file test_data_reader.hpp
 * @brief Header-only reader for MPFloat validation test data files
 * 
 * Reads binary test data files generated by generate_test_data.py
 * 
 * File format:
 *   Header (32 bytes):
 *     - magic: 4 bytes "MPFT"
 *     - version: 4 bytes (1)
 *     - precision_bits: 4 bytes
 *     - num_cases: 4 bytes
 *     - words_per_number: 4 bytes
 *     - reserved: 12 bytes
 *   
 *   Per test case:
 *     - operation: 1 byte
 *     - num_inputs: 1 byte
 *     - padding: 2 bytes
 *     - inputs: N * words_per_number * 8 bytes
 *     - expected: words_per_number * 8 bytes
 * 
 * Copyright (c) 2024 Argonne National Laboratory
 */

#ifndef MPFUN_TEST_DATA_READER_HPP
#define MPFUN_TEST_DATA_READER_HPP

#include <cstdint>
#include <cstring>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace mpfun {
namespace validation {

// Operation codes (must match generate_test_data.py)
enum class Operation : uint8_t {
    Add = 0,
    Sub = 1,
    Mul = 2,
    Div = 3,
    Sqrt = 4,
    Exp = 5,
    Log = 6,
    Sin = 7,
    Cos = 8,
    Tan = 9,
    Atan = 10
};

inline const char* operation_name(Operation op) {
    switch (op) {
        case Operation::Add: return "add";
        case Operation::Sub: return "sub";
        case Operation::Mul: return "mul";
        case Operation::Div: return "div";
        case Operation::Sqrt: return "sqrt";
        case Operation::Exp: return "exp";
        case Operation::Log: return "log";
        case Operation::Sin: return "sin";
        case Operation::Cos: return "cos";
        case Operation::Tan: return "tan";
        case Operation::Atan: return "atan";
        default: return "unknown";
    }
}

/**
 * @brief Represents a single number in MPFloat format
 */
struct MPFloatData {
    std::vector<int64_t> words;  // [sign_length, exponent, mantissa...]
    
    int64_t sign_length() const { return words.empty() ? 0 : words[0]; }
    int64_t exponent() const { return words.size() > 1 ? words[1] : 0; }
    
    int sign() const {
        auto sl = sign_length();
        return sl > 0 ? 1 : (sl < 0 ? -1 : 0);
    }
    
    int length() const {
        auto sl = sign_length();
        return static_cast<int>(sl > 0 ? sl : -sl);
    }
    
    bool is_zero() const { return sign_length() == 0; }
    
    /**
     * @brief Copy this data into an MPFloat's data array
     */
    template <int WORDS>
    void copy_to(int64_t* dest, int allocated_words, int precision_words) const {
        dest[0] = allocated_words;  // IDX_ALLOCATED
        dest[1] = precision_words;  // IDX_PRECISION
        
        // Copy sign_length and exponent
        dest[2] = words.size() > 0 ? words[0] : 0;
        dest[3] = words.size() > 1 ? words[1] : 0;
        
        // Copy mantissa words (starting at index 4)
        size_t mantissa_words = words.size() > 2 ? words.size() - 2 : 0;
        for (size_t i = 0; i < mantissa_words && i < static_cast<size_t>(allocated_words); ++i) {
            dest[4 + i] = words[2 + i];
        }
        
        // Zero remaining words
        for (size_t i = mantissa_words; i < static_cast<size_t>(allocated_words); ++i) {
            dest[4 + i] = 0;
        }
    }
};

/**
 * @brief A single test case
 */
struct TestCase {
    Operation operation;
    std::vector<MPFloatData> inputs;
    MPFloatData expected;
    
    int num_inputs() const { return static_cast<int>(inputs.size()); }
    
    bool is_binary() const {
        return operation == Operation::Add || 
               operation == Operation::Sub ||
               operation == Operation::Mul ||
               operation == Operation::Div;
    }
    
    bool is_unary() const {
        return !is_binary();
    }
};

/**
 * @brief File header information
 */
struct FileHeader {
    char magic[4];
    uint32_t version;
    uint32_t precision_bits;
    uint32_t num_cases;
    uint32_t words_per_number;
    
    bool is_valid() const {
        return magic[0] == 'M' && magic[1] == 'P' && 
               magic[2] == 'F' && magic[3] == 'T' &&
               version == 1;
    }
    
    int mantissa_words() const {
        return static_cast<int>(words_per_number) - 2;
    }
    
    int approx_decimal_digits() const {
        return static_cast<int>(precision_bits / 3.32193);
    }
};

/**
 * @brief Reader for MPFloat test data files
 */
class TestDataReader {
public:
    TestDataReader() = default;
    
    /**
     * @brief Read a test data file
     * @param path Path to the binary test data file
     * @return Vector of test cases
     * @throws std::runtime_error on file errors or invalid format
     */
    std::vector<TestCase> read_file(const std::string& path) {
        std::ifstream file(path, std::ios::binary);
        if (!file) {
            throw std::runtime_error("Failed to open file: " + path);
        }
        
        // Read header
        header_ = read_header(file);
        if (!header_.is_valid()) {
            throw std::runtime_error("Invalid file format: " + path);
        }
        
        // Read test cases
        std::vector<TestCase> cases;
        cases.reserve(header_.num_cases);
        
        for (uint32_t i = 0; i < header_.num_cases; ++i) {
            cases.push_back(read_case(file));
        }
        
        return cases;
    }
    
    /**
     * @brief Get the file header (valid after read_file)
     */
    const FileHeader& header() const { return header_; }
    
    /**
     * @brief Filter test cases by operation
     */
    static std::vector<TestCase> filter_by_op(const std::vector<TestCase>& cases, 
                                               Operation op) {
        std::vector<TestCase> filtered;
        for (const auto& c : cases) {
            if (c.operation == op) {
                filtered.push_back(c);
            }
        }
        return filtered;
    }
    
private:
    FileHeader header_{};
    
    FileHeader read_header(std::ifstream& file) {
        FileHeader h{};
        
        file.read(h.magic, 4);
        file.read(reinterpret_cast<char*>(&h.version), 4);
        file.read(reinterpret_cast<char*>(&h.precision_bits), 4);
        file.read(reinterpret_cast<char*>(&h.num_cases), 4);
        file.read(reinterpret_cast<char*>(&h.words_per_number), 4);
        
        // Skip reserved bytes (12)
        file.seekg(12, std::ios::cur);
        
        return h;
    }
    
    TestCase read_case(std::ifstream& file) {
        TestCase tc{};
        
        // Read case header
        uint8_t op_byte, num_inputs;
        file.read(reinterpret_cast<char*>(&op_byte), 1);
        file.read(reinterpret_cast<char*>(&num_inputs), 1);
        
        // Skip padding (2 bytes)
        file.seekg(2, std::ios::cur);
        
        tc.operation = static_cast<Operation>(op_byte);
        
        // Read inputs
        tc.inputs.resize(num_inputs);
        for (int i = 0; i < num_inputs; ++i) {
            tc.inputs[i] = read_mpfloat_data(file);
        }
        
        // Read expected output
        tc.expected = read_mpfloat_data(file);
        
        return tc;
    }
    
    MPFloatData read_mpfloat_data(std::ifstream& file) {
        MPFloatData data;
        data.words.resize(header_.words_per_number);
        
        for (uint32_t i = 0; i < header_.words_per_number; ++i) {
            file.read(reinterpret_cast<char*>(&data.words[i]), 8);
        }
        
        return data;
    }
};

/**
 * @brief Compare two MPFloatData values for approximate equality
 * 
 * @param a First value
 * @param b Second value
 * @param tolerance_words Number of least-significant words allowed to differ
 * @return true if values are approximately equal
 */
inline bool approximately_equal(const MPFloatData& a, const MPFloatData& b,
                                 int tolerance_words = 2) {
    // Check signs match
    if (a.sign() != b.sign()) {
        // Special case: both very close to zero
        if (a.is_zero() && b.is_zero()) return true;
        return false;
    }
    
    // Both zero
    if (a.is_zero() && b.is_zero()) return true;
    
    // Check exponents match
    if (a.exponent() != b.exponent()) {
        // Allow off-by-one if mantissas compensate
        if (std::abs(a.exponent() - b.exponent()) > 1) return false;
    }
    
    // Compare mantissa words (allowing tolerance in trailing words)
    int compare_words = std::min(a.length(), b.length());
    compare_words = std::max(1, compare_words - tolerance_words);
    
    for (int i = 0; i < compare_words && i + 2 < static_cast<int>(a.words.size()) 
                                      && i + 2 < static_cast<int>(b.words.size()); ++i) {
        if (a.words[i + 2] != b.words[i + 2]) {
            return false;
        }
    }
    
    return true;
}

/**
 * @brief Compute relative error between two MPFloatData values
 * 
 * Returns the number of matching leading mantissa words.
 * Higher is better (more precision matched).
 */
inline int matching_words(const MPFloatData& a, const MPFloatData& b) {
    if (a.sign() != b.sign()) return 0;
    if (a.is_zero() && b.is_zero()) return 999;  // Perfect match
    if (a.is_zero() || b.is_zero()) return 0;
    if (a.exponent() != b.exponent()) return 0;
    
    int matches = 0;
    int compare_len = std::min({a.length(), b.length(), 
                                static_cast<int>(a.words.size()) - 2,
                                static_cast<int>(b.words.size()) - 2});
    
    for (int i = 0; i < compare_len; ++i) {
        if (a.words[i + 2] == b.words[i + 2]) {
            matches++;
        } else {
            break;
        }
    }
    
    return matches;
}

} // namespace validation
} // namespace mpfun

#endif // MPFUN_TEST_DATA_READER_HPP
